{% set name = "jupyverse" %}
{% set version = "0.14.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a9bf576e64f1ff89a23062821f33affbc69a695ad4fb374a865625d1d0362b8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build
  run:
    - python >={{ python_min }}
    - anycorn >=0.18.6,<0.19.0
    - fastapi-core >=0.136.0,<1.0.0
    - fps >=0.6.3,<0.7.0
    - fps-contents >=0.11.2,<0.12.0
    - fps-file-watcher >=0.2.0,<0.3.0
    - fps-kernel-subprocess >=0.2.2,<0.3.0
    - fps-kernels >=0.11.3,<0.12.0
    - fps-terminals >=0.10.0,<0.11.0
    - fps-nbconvert >=0.10.0,<0.11.0
    - fps-lab >=0.11.4,<0.12.0
    - fps-frontend >=0.10.0,<0.11.0
    - rich-click >=1.6.1,<2

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - jupyverse
  commands:
    - pip check
    - jupyverse --help

about:
  home: https://github.com/jupyter-server/jupyverse
  summary: A set of FPS modules implementing a Jupyter server
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse
  doc_url: https://jupyter-server.github.io/jupyverse
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
