{% set name = "jupyverse" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 48aa3b1b47f1e802915a153823b112b55896c5d1c934a88faa1bbbfa7de8c689

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - fps-contents >=0.1.9,<1
    - fps-kernels >=0.1.9,<1
    - fps-terminals >=0.1.9,<1
    - fps-nbconvert >=0.1.9,<1
    - fps-yjs >=0.1.9,<1
    - fps-lab >=0.1.9,<1
    - fps-frontend >=0.1.9,<1
    - jupyverse-api >=0.1.9,<1

test:
  imports:
    - jupyverse

about:
  home: https://github.com/jupyter-server/jupyverse
  summary: A set of Asphalt components implementing a Jupyter server
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse
  doc_url: https://davidbrochart.github.io/jupyverse
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
