{% set name = "jupyverse" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0885f2e78e05f44a6cbf824bbf03f0c7d020a1dfdefcece78d74483c0abde294

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - fps-contents >=0.8.0,<0.9.0
    - fps-kernels >=0.8.0,<0.9.0
    - fps-terminals >=0.8.0,<0.9.0
    - fps-nbconvert >=0.8.0,<0.9.0
    - fps-yjs >=0.8.0,<0.9.0
    - fps-lab >=0.8.0,<0.9.0
    - fps-frontend >=0.8.0,<0.9.0
    - jupyverse-api >=0.8.0,<0.9.0
    - rich-click >=1.6.1,<2
    - fastapi
    - anycorn >=0.18.1,<0.19.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - jupyverse

about:
  home: https://github.com/jupyter-server/jupyverse
  summary: A set of FPS modules implementing a Jupyter server
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse
  doc_url: https://davidbrochart.github.io/jupyverse
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
