{% set name = "jupyverse" %}
{% set version = "0.0.47" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3362ecdbb240c28f76db2e156e6b0d2914aec287070e622b351c1edc0f9841c1

build:
  noarch: python
  number: 0
  entry_points:
    - jupyverse = fps_uvicorn.cli:app
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - fastapi >=0.87.0,<1
    - fps >=0.0.21,<1
    - fps-uvicorn >=0.0.19,<1
    - fps-auth-base <1
    - fps-contents >=0.0.37,<1
    - fps-kernels >=0.0.37,<1
    - fps-terminals >=0.0.37,<1
    - fps-nbconvert >=0.0.37,<1
    - fps-yjs >=0.0.37,<1

test:
  commands:
    - jupyverse --help

about:
  home: https://github.com/jupyter-server/jupyverse
  summary: A set of FPS plugins implementing a Jupyter server
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
