{% set name = "jupyverse" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f6111d06d90f150e74b8808f1c599d5e32d80eee37ac843fa25533f8812de27

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - fps-contents >=0.7.8,<1
    - fps-kernels >=0.7.8,<1
    - fps-terminals >=0.7.8,<1
    - fps-nbconvert >=0.7.8,<1
    - fps-yjs >=0.7.8,<1
    - fps-lab >=0.7.8,<1
    - fps-frontend >=0.7.8,<1
    - jupyverse-api >=0.7.8,<1

test:
  requires:
    - python {{ python_min }}
  imports:
    - jupyverse

about:
  home: https://github.com/jupyter-server/jupyverse
  summary: A set of FPS modules implementing a Jupyter server
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse
  doc_url: https://davidbrochart.github.io/jupyverse
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
