{% set name = "jupyverse" %}
{% set version = "0.0.38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f8069af33a2d4f3ccacfa8f46855f19ee825324bcbfe92e4c152041f8e28b72

build:
  noarch: python
  number: 1
  entry_points:
    - jupyverse = fps_uvicorn.cli:app
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fastapi >=0.82.0,<1
    - fps >=0.0.19,<1
    - fps-uvicorn >=0.0.19,<1
    - fps-contents >=0.0.37,<1
    - fps-kernels >=0.0.37,<1
    - fps-terminals >=0.0.37,<1
    - fps-nbconvert >=0.0.37,<1
    - fps-yjs >=0.0.37,<1

test:
  commands:
    - jupyverse --help

about:
  home: https://github.com/jupyter-server/jupyverse
  summary: A set of FPS plugins implementing a Jupyter server
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
