{% set name = "jupyverse" %}
{% set version = "0.10.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b11d102da2353c162a86a81a1b68cd67d23b51d49918d18b7166f3eaadf03ea

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - fps >=0.5.1,<0.6.0
    - fps-contents >=0.10.0,<0.11.0
    - fps-file-id >=0.2.1,<0.3.0
    - fps-kernel-subprocess >=0.1.1,<0.2.0
    - fps-kernels >=0.9.1,<0.10.0
    - fps-terminals >=0.9.0,<0.10.0
    - fps-nbconvert >=0.9.0,<0.10.0
    - fps-yjs >=0.10.2,<0.11.0
    - fps-lab >=0.9.0,<0.10.0
    - fps-frontend >=0.9.0,<0.10.0
    - jupyverse-api >=0.10.3,<0.11.0
    - rich-click >=1.6.1,<2
    - fastapi-core
    - anycorn >=0.18.1,<0.19.0
    - watchfiles >=1.0.4,<2.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - jupyverse
  commands:
    - jupyverse --help

about:
  home: https://github.com/jupyter-server/jupyverse
  summary: A set of FPS modules implementing a Jupyter server
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse
  doc_url: https://jupyter-server.github.io/jupyverse
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
