{% set name = "jupyverse" %}
{% set version = "0.0.36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed22b5e905f8216e71d76946bc5e404f2d9a758d67b3a870b9e53b130b32c061

build:
  noarch: python
  number: 0
  entry_points:
    - jupyverse = fps_uvicorn.cli:app
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fps >=0.0.19<1
    - fps-uvicorn >=0.0.19,<1
    - fps-contents <1
    - fps-kernels <1
    - fps-terminals <1
    - fps-nbconvert <1
    - fps-yjs <1

test:
  commands:
    - jupyverse --help

about:
  home: https://github.com/jupyter-server/jupyverse
  summary: A set of FPS plugins implementing a Jupyter server
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
