{% set name = "jupyverse" %}
{% set version = "0.10.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a82a264135efbb659cbfd33b93bdc5a0274caa3099884e15bf00729c6247d4f5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build
  run:
    - python >={{ python_min }}
    - fps >=0.5.2,<0.6.0
    - fps-contents >=0.10.3,<0.11.0
    - fps-file-id >=0.3.4,<0.4.0
    - fps-file-watcher >=0.1.3,<0.2.0
    - fps-kernel-subprocess >=0.1.5,<0.2.0
    - fps-kernels >=0.10.5,<0.11.0
    - fps-terminals >=0.9.3,<0.10.0
    - fps-nbconvert >=0.9.3,<0.10.0
    - fps-yjs >=0.11.3,<0.12.0
    - fps-lab >=0.9.6,<0.10.0
    - fps-frontend >=0.9.3,<0.10.0
    - jupyverse-api >=0.12.4,<0.13.0
    - rich-click >=1.6.1,<2
    - fastapi-core
    - anycorn >=0.18.1,<0.19.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - jupyverse
  commands:
    - pip check
    - jupyverse --help

about:
  home: https://github.com/jupyter-server/jupyverse
  summary: A set of FPS modules implementing a Jupyter server
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse
  doc_url: https://jupyter-server.github.io/jupyverse
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
