{% set name = "jupyverse" %}
{% set version = "0.0.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13fd38d9d16350e05c267c3e7e87a98d9773dfe20aed295926ec5b2ec229ea19

build:
  noarch: python
  number: 0
  entry_points:
    - jupyverse = fps_uvicorn.cli:app
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fps >=0.0.8,<0.1.0
    - fps-uvicorn <0.1.0
    - fps-login >=0.0.32,<0.1.0
    - fps-auth >=0.0.32,<0.1.0
    - fps-contents >=0.0.32,<0.1.0
    - fps-kernels >=0.0.32,<0.1.0
    - fps-terminals >=0.0.32,<0.1.0
    - fps-nbconvert >=0.0.32,<0.1.0
    - fps-yjs >=0.0.32,<0.1.0

test:
  commands:
    - jupyverse --help

about:
  home: https://github.com/jupyter-server/jupyverse
  summary: A set of FPS plugins implementing a Jupyter server
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
