{% set name = "jupyverse" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f0b1c66b7f291c1743c4333c54fb723aa5367fe32999c26e22e97995540d8875

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - fps-contents >=0.1.4,<1
    - fps-kernels >=0.1.4,<1
    - fps-terminals >=0.1.4,<1
    - fps-nbconvert >=0.1.4,<1
    - fps-yjs >=0.1.4,<1
    - fps-lab >=0.1.4,<1
    - fps-frontend >=0.1.4,<1
    - jupyverse-api >=0.1.4,<1

test:
  imports:
    - jupyverse

about:
  home: https://github.com/jupyter-server/jupyverse
  summary: A set of Asphalt components implementing a Jupyter server
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
